### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by shams2023** [cswry/SeeSR#1]
Hello!
When will the code be released?
thanks

**Comment by cswry** [comment]
Hello, we will open source the training code and training data before the end of December.

**Comment by shams2023** [comment]
> Hello, we will open source the training code and training data before the end of December.

Okay, I'm really looking forward to your results!

**Comment by zelenooki87** [comment]
what about inference speed and vram consumption? vs diffbir?
by training code you mean and testing code? for model evaluation? Thanks

**Comment by cswry** [comment]
> what about inference speed and vram consumption? vs diffbir? by training code you mean and testing code? for model evaluation? Thanks

Yes, in our release, it will include the inference time and VRAM consumption. As for diffbir, you can refer to our implementation approach and test it using the official code of diffbir.

**Comment by cswry** [comment]
We have released the codes and the pretrained models. Thanks for your attention. 😊😊😊
