### ISSUE TITLE
OSError: Error no file named diffusion_pytorch_model.bin found in directory preset/models/seesr.

### ISSUE THREAD

**Issue by crazydiamondaz** [cswry/SeeSR#15]
Thanks for your greatwork. I put the weight in the dir like this:
/SeeSR-main/preset/models
  --DAPE.pth 
  --seesr
  --stable-diffusion-2-base
 And run the command:
python test_seesr.py \
--pretrained_model_path preset/models/stable-diffusion-2-base \
--prompt None \
--seesr_model_path preset/models/seesr \
--ram_ft_path preset/models/DAPE.pth \
--image_path preset/datasets/test_datasets \
--output_dir preset/datasets/output \
--start_point lr \
--num_inference_steps 50 \
--guidance_scale 5.5 \
--process_size 512 
However, it turns out to be OSError:Error no file named diffusion_pytorch_model.bin found in directory preset/models/seesr.
How can i fix this problem? Thanks a lot.

**Comment by ningbende** [comment]
me too!

**Comment by dillfrescott** [comment]
Same issue!

**Comment by shams2023** [comment]
+1

**Comment by huangyang-666** [comment]
Thank you for your prompt reply. I solved the issue by manually downloading each file of seesr and placing them in the corresponding location under 'preset/models/seesr'.
