### ISSUE TITLE
seesr数据制作脚本问题

### ISSUE THREAD

**Issue by sunzhe09** [cswry/SeeSR#20]
python utils_data/make_paired_data.py \
--gt_path PATH_1 PATH_2 ... \
--save_dir preset/datasets/train_datasets/training_for_dape \
--epoch 1
这里保存目录是不是应该改成preset/datasets/train_datasets/training_for_seesr，否则会覆盖DPAE的数据

**Comment by cswry** [comment]
嗯嗯，是的。

**Comment by aulaywang** [comment]
我有个问题，为什么在处理SeeSR数据的时候发现，文件夹创建了，但是图像并没有保存到对应文件夹中？
