### ISSUE TITLE
The super resolution result of the given test image is blur. No errors are reported. I wonder where I may go wrong?

### ISSUE THREAD

**Issue by CXNing** [cswry/SeeSR#23]
![微信截图_20240229115633](https://github.com/cswry/SeeSR/assets/34532962/da5866a7-8ce1-4d51-8ca2-79f6e1d4b6f4)

**Comment by cswry** [comment]
Hello, can you provide the resolution of input image?

**Comment by CXNing** [comment]
128*128, it's the image in preset/datasets/test_datasets

**Comment by CXNing** [comment]
So what's the possible reason? The wrong checkpoint? But the model is loaded without any errors.

**Comment by CXNing** [comment]
Yes, the problem still exists. Strange, I re-downloaded the model and the result is still the same.

**Comment by CXNing** [comment]
The tag is “animal, pink, stone, salamander, None,clean, high-resolution, 8k,"  right? Does the None tag influences the result?

**Comment by cswry** [comment]
> The tag is “animal, pink, stone, salamander, None,clean, high-resolution, 8k," right? Does the None tag influences the result?

What would happen if you delete 'none'?

Normally, DAPE won't predict 'none', I guess you mistakenly set the text in the user prompt.

**Comment by noir94** [comment]
I have the same results.. Have you solved this problem?

**Comment by CXNing** [comment]
> I have the same results.. Have you solved this problem?

No
