### ISSUE TITLE
argument about '--use_ram_encoder'

### ISSUE THREAD

**Issue by striveAgain** [cswry/SeeSR#24]
Hello, thank you for sharing the code of SeeSR! 
When I read it, I found it did not seem to perform cross attention between the 'ram_encoder_hidden_states' and the resnet output during training.
The screen shot is as follows, please give me some advice.

From your command
`CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7," accelerate launch train_seesr.py \
--pretrained_model_name_or_path="preset/models/stable-diffusion-2-base" \
--output_dir="./experience/seesr" \
--root_folders 'preset/datasets/training_datasets' \
--ram_ft_path 'preset/models/DAPE.pth' \
--enable_xformers_memory_efficient_attention \
--mixed_precision="fp16" \
--resolution=512 \
--learning_rate=5e-5 \
--train_batch_size=2 \
--gradient_accumulation_steps=2 \
--null_text_ratio=0.5 
--dataloader_num_workers=0 \
--checkpointing_steps=10000 `,
there's no `----use_ram_encoder`.

Thus, 
![image](https://github.com/cswry/SeeSR/assets/105333061/59de1631-119e-40d2-8f08-2c915a283659)
`use_image_cross_attention` will be `False`.
![image](https://github.com/cswry/SeeSR/assets/105333061/471cb629-ce33-4dc6-85ef-8a5f48dce31f)

While forwarding,
![image](https://github.com/cswry/SeeSR/assets/105333061/681d70e5-6c56-435c-8ced-c3dd8971aac8)
![image](https://github.com/cswry/SeeSR/assets/105333061/c1dc5a31-8e8f-4b53-85c9-659e155b4e32)
it will skip to `else`, omitting the `image_encoder_hidden_states`.

Please give me some instructions, thanks!

**Comment by cswry** [comment]
Hello, the param `use_image_cross_attention` is set to `True` by default.

I have deleted the redundant param `use_ram_encoder`， please refer to the latest version.

Thanks for your remind!

**Comment by striveAgain** [comment]
OK, I have updated the latest code. Thank you!
