### ISSUE TITLE
Can not load the unet and controlnet

### ISSUE THREAD

**Issue by XsherryR** [cswry/SeeSR#3]
Thanks for your wonderful work! I'm encountering an error when trying to load the 'unet' or 'controlnet' models. The error mentions that it couldn't connect to 'https://huggingface.co/' to load the model, even though I believe my internet connection is working fine. Do you have any suggestions on how to fix this issue?

The error message is as follows:
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like preset/models/seesr is not the path to a directory containing a config.json file. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

**Comment by flynnamy** [comment]
Hi,same problem! How to solve this? Thanks! @XsherryR

**Comment by CuddleSabe** [comment]
> Hi,same problem! How to solve this? Thanks! @XsherryR

replace the relative path to absolute path

**Comment by flynnamy** [comment]
Could you explain it in details? @CuddleSabe
