### ISSUE TITLE
Not work for people

### ISSUE THREAD

**Issue by CuddleSabe** [cswry/SeeSR#4]
![00004](https://github.com/cswry/SeeSR/assets/61224076/31c054a4-8d14-4d96-92f0-fe8935151c8e)

**Comment by CuddleSabe** [comment]
Too scary...
<img width="389" alt="截屏2023-12-26 17 19 44" src="https://github.com/cswry/SeeSR/assets/61224076/8468368e-c2f2-49e1-8186-0268b79fd4ef">

**Comment by cswry** [comment]
Hello, can you provide the corresponding LR image and the corresponding inference command？

**Comment by CuddleSabe** [comment]
![00004](https://github.com/cswry/SeeSR/assets/61224076/6b03f0df-6fa0-42c1-8d13-5b1850669de6)
![0012](https://github.com/cswry/SeeSR/assets/61224076/16a81145-a5f9-4aa6-ab57-52d3ffeba277)
the command params are default

**Comment by CuddleSabe** [comment]
they all have mpeg degradation

**Comment by cswry** [comment]
![person2](https://github.com/cswry/SeeSR/assets/111725164/1e35d380-1c1d-404a-9fd4-b05deeb8d110)
![person1](https://github.com/cswry/SeeSR/assets/111725164/bdcb100e-2840-419b-93f4-0e94b7c34f7b)

Hello, the two images above are the test results obtained on our end using the default command settings.
There are significant differences between our test results and yours. 

We observe that the resolution of your provided super-resolution results is equal to the resolution of your input images. 
Please make sure to set the `--upscale` to 4 during the inference. 

There is room for improvement in the facial results of the second image, which could be attributed to two possible reasons.
- During our training, we only simulated degradation such as noise, blur, and jpeg compression following `RealESRGAN pipeline`. For unknown degradations like mpeg degradation, the model's generalization ability is limited. 
- The currently open-source model is trained for general scenarios and may have limited performance in specialized scenarios such as face. In the future, we are planning to train a specialized version called `SeeSR-face` specifically for facial scenarios. Please stay tuned for updates on this.

**Comment by CuddleSabe** [comment]
> ![person2](https://private-user-images.githubusercontent.com/111725164/292861989-1e35d380-1c1d-404a-9fd4-b05deeb8d110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTUyODEsIm5iZiI6MTcwMzU5NDk4MSwicGF0aCI6Ii8xMTE3MjUxNjQvMjkyODYxOTg5LTFlMzVkMzgwLTFjMWQtNDA0YS05ZmQ0LWIwNWRlZWI4ZDExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxMjQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzFiYWM1OWQ0NTZjYjFmMTQzZGNkM2E0OGU5MGMzODFmNWRhNjQxM2M5ZjZiNzE2MjY0ZjAyOTU1ODgzZjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZOi8SJQGLs03Y_U9rKIIELsSmfmo7o-8R5a5reaTZtc) ![person1](https://private-user-images.githubusercontent.com/111725164/292861982-bdcb100e-2840-419b-93f4-0e94b7c34f7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTUyODEsIm5iZiI6MTcwMzU5NDk4MSwicGF0aCI6Ii8xMTE3MjUxNjQvMjkyODYxOTgyLWJkY2IxMDBlLTI4NDAtNDE5Yi05M2Y0LTBlOTRiN2MzNGY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxMjQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTcxYzI0NDBjMWI3MDEwZWNmMzdhOWU3Mjk0ZDgwZDk2YmNjNzA5OGJjYzlkYmM1MWFhYzcxNDI1M2U3ZTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8f6kx6Pu1g_2dGRRboHXGbHVAiTTLc9HxZHfOjiScBU)
> 
> Hello, the two images above are the test results obtained on our end using the default command settings. There are significant differences between our test results and yours.
> 
> We observe that the resolution of your provided super-resolution results is equal to the resolution of your input images. Please make sure to set the `--upscale` to 4 during the inference.
> 
> There is room for improvement in the facial results of the second image, which could be attributed to two possible reasons.
> 
> * During our training, we only simulated degradation such as noise, blur, and jpeg compression following `RealESRGAN pipeline`. For unknown degradations like mpeg degradation, the model's generalization ability is limited.
> * The currently open-source model is trained for general scenarios and may have limited performance in specialized scenarios such as face. In the future, we are planning to train a specialized version called `SeeSR-face` specifically for facial scenarios. Please stay tuned for updates on this.

thank for your reply!
well, thats the confusion. Due to my experience, the x1 model use the Real-ESRGAN degradation has the capacity to process the 4x up sample input(because of the resize process in degradation), but why the x4 model can't process the x1 sample input?
LOL

**Comment by cswry** [comment]
> > ![person2](https://private-user-images.githubusercontent.com/111725164/292861989-1e35d380-1c1d-404a-9fd4-b05deeb8d110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTUyODEsIm5iZiI6MTcwMzU5NDk4MSwicGF0aCI6Ii8xMTE3MjUxNjQvMjkyODYxOTg5LTFlMzVkMzgwLTFjMWQtNDA0YS05ZmQ0LWIwNWRlZWI4ZDExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxMjQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzFiYWM1OWQ0NTZjYjFmMTQzZGNkM2E0OGU5MGMzODFmNWRhNjQxM2M5ZjZiNzE2MjY0ZjAyOTU1ODgzZjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZOi8SJQGLs03Y_U9rKIIELsSmfmo7o-8R5a5reaTZtc) ![person1](https://private-user-images.githubusercontent.com/111725164/292861982-bdcb100e-2840-419b-93f4-0e94b7c34f7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTUyODEsIm5iZiI6MTcwMzU5NDk4MSwicGF0aCI6Ii8xMTE3MjUxNjQvMjkyODYxOTgyLWJkY2IxMDBlLTI4NDAtNDE5Yi05M2Y0LTBlOTRiN2MzNGY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxMjQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTcxYzI0NDBjMWI3MDEwZWNmMzdhOWU3Mjk0ZDgwZDk2YmNjNzA5OGJjYzlkYmM1MWFhYzcxNDI1M2U3ZTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8f6kx6Pu1g_2dGRRboHXGbHVAiTTLc9HxZHfOjiScBU)
> > Hello, the two images above are the test results obtained on our end using the default command settings. There are significant differences between our test results and yours.
> > We observe that the resolution of your provided super-resolution results is equal to the resolution of your input images. Please make sure to set the `--upscale` to 4 during the inference.
> > There is room for improvement in the facial results of the second image, which could be attributed to two possible reasons.
> > 
> > * During our training, we only simulated degradation such as noise, blur, and jpeg compression following `RealESRGAN pipeline`. For unknown degradations like mpeg degradation, the model's generalization ability is limited.
> > * The currently open-source model is trained for general scenarios and may have limited performance in specialized scenarios such as face. In the future, we are planning to train a specialized version called `SeeSR-face` specifically for facial scenarios. Please stay tuned for updates on this.
> 
> thank for your reply! well, thats the confusion. Due to my experience, the x1 model use the Real-ESRGAN degradation has the capacity to process the 4x up sample input(because of the resize process in degradation), but why the x4 model can't process the x1 sample input? LOL

SeeSR operates a diffusion process within the latent space. 

When you input an x1 LR image, its inherent low resolution diminish more after undergoing VAE Encoder compression (spatial resolution reduced by 8 times). In such a state, it is difficult to sustain the spatial structure within the limited latent space. 

It induces the model towards uncontrollable generation, which also explains why the second facial image appear somewhat strange.
