### ISSUE TITLE
sd-turbo版本的技术上的疑问（请教）

### ISSUE THREAD

**Issue by Feynman1999** [cswry/SeeSR#40]
你好，请问sd-turbo版本是需要重新训练controlNET吗？（时间步设置为2）还是说只需要把之前SD2.1训练好的用上去就行（只是更换SD的部分）

**Comment by Feynman1999** [comment]
看代码应该是同一套参数，只是换sd部分为sd-turbo就可以了？ 
作为萌新想问下，技术上该如何理解不需要变更controlnet的参数也可以work？

**Comment by cswry** [comment]
嗯嗯，把基于sd2-base训练的controlnet和sd-turbo进行组合。
这个目前只是一个观察，发现直接更换基础模型可以继承到sd-turbo少步数的优势，但结果略糊。
类似的观察在LCM-lora中也存在，基于lcm训练的lora可以直接和其它基于base模型训练的style lora进行组合。
