### ISSUE TITLE
FID problem

### ISSUE THREAD

**Issue by striveAgain** [cswry/SeeSR#45]
Hello, thank you for sharing the code of SeeSR! That's an amazing work indeed!

When I tried to calculate the metric FID using the code proposed in `basicsr/metrics/fid.py`, the result was quite confusing.

Here is how I calculate the metric FID. If any problem, feel free to point out.
![image](https://github.com/cswry/SeeSR/assets/105333061/99542b86-624f-4e1c-b311-2a642d4ca683)

First, I defined a function which outputs a list composed of all images.
![image](https://github.com/cswry/SeeSR/assets/105333061/f53d6ccd-eb08-4f45-803b-4cd0e96e41e5)
Then, I processed SR images and GT images, respectively, using `inception_v3` to extract features and calculating FID.

As for the results, when the param `normalize_input` set to False, I got `FID = 118.71415109991415`.
And when the param `normalize_input` set to True, I got `FID = 126.1874280351401`.

Both of them are quite higher than the paper mentioned, this makes me realize which step seems to have gone wrong.
Could you please give me some advice? And whether the param `normalize_input` should be set to True or not?

Thanks a lot!

**Comment by cswry** [comment]
Hello, I use pyiqa for metrics calculating, please follow the instruction of [IQA-PyTorch](https://github.com/chaofengc/IQA-PyTorch)

**Comment by ryanxingql** [comment]
BTW, I think the FID calculation on a small-scale dataset is not appropriate. [ref](https://github.com/bioinf-jku/TTUR/issues/4#issuecomment-346322417)
