### ISSUE TITLE
OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

### ISSUE THREAD

**Issue by ConanMusk** [cswry/SeeSR#56]
请问有关'bert-base-uncased'无法导入的问题如何解决？

**Comment by ConanMusk** [comment]
已经解决了，将bert-base-uncased文件夹的位置告诉网络就行，比如：
    tokenizer = BertTokenizer.from_pretrained('/workspace/seesr/preset/models/bert-base-uncased')

**Comment by Renzhihan** [comment]
请问preset/models/ram_swin_large_14m.pth这个模型是在哪里下载的呢？

**Comment by cswry** [comment]
> 请问preset/models/ram_swin_large_14m.pth这个模型是在哪里下载的呢？

https://huggingface.co/spaces/xinyu1205/recognize-anything/blob/main/ram_swin_large_14m.pth
