### ISSUE TITLE
How many epochs do you set when creating training datasets?

### ISSUE THREAD

**Issue by XsherryR** [cswry/SeeSR#6]
The default setting is 1; is this sufficient for fine-tuning the model?

**Comment by cswry** [comment]
By default, it is set to 1, but this is definitely not enough for training. 

It requires finding a balance between memory consumption and training data diversity.

**Comment by XsherryR** [comment]
> By default, it is set to 1, but this is definitely not enough for training.
> 
> It requires finding a balance between memory consumption and training data diversity.

Could you tell me how many epochs you set when creating training datasets?

**Comment by cswry** [comment]
> > By default, it is set to 1, but this is definitely not enough for training.
> > It requires finding a balance between memory consumption and training data diversity.
> 
> Could you tell me how many epochs you set when creating training datasets?

It could be 60? It has been a long time since the data was created from now.

**Comment by XsherryR** [comment]
> > > By default, it is set to 1, but this is definitely not enough for training.
> > > It requires finding a balance between memory consumption and training data diversity.
> > 
> > 
> > Could you tell me how many epochs you set when creating training datasets?
> 
> It could be 60? It has been a long time since the data was created from now.

Got it, thanks！
