### ISSUE TITLE
Question about the output of vae.encode

### ISSUE THREAD

**Issue by XsherryR** [cswry/SeeSR#7]
The input to vae.encode is 'pixel_values' [2, 3, 512, 512], however, the output 'latents' is [2, 4, 64, 64]. Why is the channel dimension different?

**Comment by cswry** [comment]
Hello, Stable Diffusion 2-1 downsamples the image to the latent space, just from 3x512x512 to 4x64x64.

For more details, you can refer to the [paper](https://arxiv.org/abs/2112.10752).

**Comment by XsherryR** [comment]
Thanks for your reply! I want to know the code in the train_seesr.py whether using EMA to save the model parameters?

**Comment by cswry** [comment]
Hello, we do not use EMA strategy.

**Comment by XsherryR** [comment]
Would you be able to provide instructions on how to adjust the code in the train_seesr.py to incorporate EMA for parameter saving?

**Comment by XsherryR** [comment]
> Hello, we do not use EMA strategy.

Would you be able to provide instructions on how to adjust the code in the train_seesr.py to incorporate EMA for parameter saving?

**Comment by cswry** [comment]
> > Hello, we do not use EMA strategy.
> 
> Would you be able to provide instructions on how to adjust the code in the train_seesr.py to incorporate EMA for parameter saving?

Our codes are based on the diffusers, if you want to add EMA function, you may refer [this](https://github.com/huggingface/diffusers/blob/main/src/diffusers/training_utils.py).
