### ISSUE TITLE
When input image is 480 * 960,  there is   CUDA out of memory error. 

### ISSUE THREAD

**Issue by wtt5220150** [cswry/SeeSR#9]

**Comment by cswry** [comment]
Hello, can you provide the GPU model, VRAM, and specific details of the error message?

**Comment by wtt5220150** [comment]
We use V100, VGAM is 32G. When debugging with breakpoints,  CUDA out of memory error occurred "latents_condition_image = self.vae.encode(image*2-1).latent_dist.sample()"

**Comment by wtt5220150** [comment]
Are there any restrictions on input resolution？

**Comment by cswry** [comment]
> Are there any restrictions on input resolution？

Hello, we have updated vae_encoder tile function. It would be need 13G VRAM when vae_encoder tile size is set to 1024.

**Comment by wtt5220150** [comment]
Thanks ,the problem is solved

**Comment by cswry** [comment]
> Thanks ,the problem is solved

Thank you also for providing the cases that helped us improve the code.
